done
Strikersoft/strikersoft-frontend-test-assignment pull request #3
Opened 2017-11-27 19:32 UTC by Maksymyr

2017-11-27 19:37 UTC, KatSick commented
Hi,

Thanks for submitting PR!

Can you deploy this app using github pages, surge or now to check functionality ?

2017-11-28 00:21 UTC, KatSick requested changes
There is some changes required to pass test assignment.

2017-11-28 00:21 UTC, KatSick commented on src/App.js
> +      this.setState({
It looks like this two `setState`s can be merged into one

2017-11-28 00:21 UTC, KatSick commented on src/App.js
> +    let array = this.state.searched.length == 0 ? this.state.data : !this.state.checkSearch ? this.state.searched : this.state.data;
consider using `const` instead of `let`

2017-11-28 00:21 UTC, KatSick commented on src/App.js
> +    let array = this.state.searched.length == 0 ? this.state.data : !this.state.checkSearch ? this.state.searched : this.state.data;
looks like this checks is duplicated in several methods, what about DRY (Do not repeat yourself) practice ?

2017-11-28 00:21 UTC, KatSick commented on src/App.js
> +    search.length == 0 ? this.setState({checkSearch: true, searched: [], item: {}}) :
same regarding doubled `setState`s

2017-11-28 00:21 UTC, KatSick commented on src/App.js
> +    this.setState({item: item})
Try to use object literal property value shorthand here like `this.setState({ item });`

2017-11-28 00:21 UTC, Maksymyr commented
Hello, Ostap!
Sorry for late message, but I didn't expect your answer today))
Just recently saw it :(
I put it here:
https://maksymyr.github.io/strikersoft-frontend-test-assignment/

Thank you for allotted time and good night!

Kind regards,
Maksym

2017-11-27 21:37 GMT+02:00 Ostap Chervak <notifications@github.com>:

> Hi,
>
> Thanks for submitting PR!
>
> Can you deploy this app using github pages, surge or now to check
> functionality ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Strikersoft/strikersoft-frontend-test-assignment/pull/3#issuecomment-347301328>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AeeUcow0tq-BaOvW_LgVFV9ui3JVLyucks5s6w-VgaJpZM4QsKtI>
> .
>

2017-11-28 00:23 UTC, KatSick commented
@Maksymyr not a problem. checked your URL. looks OK.
however, i have some questions on your code. please check out review above.

2017-11-28 00:26 UTC, Maksymyr commented
I saw, thank you for feedback!
I'll inspect and improve it. Trying to make it faster I made many extra

2017-11-28 2:23 GMT+02:00 Ostap Chervak <notifications@github.com>:

> @Maksymyr <https://github.com/maksymyr> not a problem. checked your URL.
> looks OK.
> however, i have some questions on your code. please check out review above.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Strikersoft/strikersoft-frontend-test-assignment/pull/3#issuecomment-347373032>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AeeUcjAjpUKkRY6GjYmJC0kQ-JaO3cvJks5s61JtgaJpZM4QsKtI>
> .
>

2017-11-28 00:28 UTC, KatSick commented
@Maksymyr thanks for your motivation to make it better, however our goal is to finilize your codebase.
try to resolve my small comments and thats all.

2017-11-28 00:30 UTC, Maksymyr commented
Be sure, I'll study it now, but I'll probably fix it tomorrow.
My gratitude for conveying of your experience!

2017-11-28 2:28 GMT+02:00 Ostap Chervak <notifications@github.com>:

> @Maksymyr <https://github.com/maksymyr> thanks for your motivation to
> make it better, however our goal is to finilize your codebase.
> try to resolve my small comments and thats all.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Strikersoft/strikersoft-frontend-test-assignment/pull/3#issuecomment-347373830>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AeeUcl3FGwemw2kv_6od4UO7nNLpumIfks5s61OUgaJpZM4QsKtI>
> .
>

2017-11-28 16:09 UTC, KatSick approved these changes

2017-11-28 16:09 UTC, KatSick commented
@Maksymyr thanks for your feedback. looks ok for me

2017-11-28 16:09 UTC, closed without merging

2017-11-28 16:19 UTC, Maksymyr commented
Thank you for comments and attention, Ostap! 
Best regards!